// Common primary-care presenting complaints (type-ahead suggestions).
export const COMPLAINTS: string[] = [
  "Fever",
  "Cough",
  "Cold / coryza",
  "Sore throat",
  "Runny nose",
  "Nasal congestion",
  "Sneezing",
  "Headache",
  "Body aches",
  "Generalized weakness",
  "Fatigue",
  "Shortness of breath",
  "Wheezing",
  "Chest pain",
  "Palpitations",
  "Abdominal pain",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Constipation",
  "Heartburn / acidity",
  "Loss of appetite",
  "Dizziness / vertigo",
  "Back pain",
  "Joint pain",
  "Muscle pain",
  "Neck pain",
  "Skin rash",
  "Itching",
  "Earache",
  "Eye redness",
  "Burning micturition",
  "Frequent urination",
  "Painful urination",
  "Weight loss",
  "Weight gain",
  "Swelling of feet",
  "Anxiety",
  "Insomnia",
  "Toothache",
  "Sore eyes",
  "Vomiting blood",
];

// Common primary-care diagnoses (type-ahead suggestions).
export const DIAGNOSES: string[] = [
  "Upper respiratory tract infection (URTI)",
  "Acute pharyngitis",
  "Acute tonsillitis",
  "Acute bronchitis",
  "Pneumonia",
  "Asthma exacerbation",
  "COPD",
  "Allergic rhinitis",
  "Acute sinusitis",
  "Otitis media",
  "Conjunctivitis",
  "Acute gastroenteritis",
  "Acid peptic disease / GERD",
  "Urinary tract infection (UTI)",
  "Hypertension",
  "Type 2 diabetes mellitus",
  "Dyslipidemia",
  "Migraine",
  "Tension headache",
  "Anemia",
  "Hypothyroidism",
  "Dengue fever",
  "Typhoid / enteric fever",
  "Malaria",
  "Viral fever",
  "COVID-19",
  "Dermatitis / eczema",
  "Fungal skin infection",
  "Scabies",
  "Cellulitis",
  "Osteoarthritis",
  "Mechanical low back pain",
  "Sciatica",
  "Gout",
  "Anxiety disorder",
  "Depression",
  "Vertigo (BPPV)",
  "Hemorrhoids",
  "Worm infestation",
  "Vitamin D deficiency",
];

// Co-morbidities checklist (matches the printed prescription pad).
export const CO_MORBS: string[] = [
  "HTN",
  "DM",
  "TB",
  "Hep B",
  "Hep C",
  "Asthma",
  "IHD",
  "CKD",
];
