// Common primary-care presenting complaints (type-ahead suggestions).
export const COMPLAINTS: string[] = [
  "Fever",
  "High-grade fever",
  "Low-grade fever",
  "Fever with chills / rigors",
  "Cough",
  "Dry cough",
  "Productive cough",
  "Cough with blood",
  "Cold / coryza",
  "Sore throat",
  "Runny nose",
  "Nasal congestion",
  "Sneezing",
  "Loss of smell / taste",
  "Hoarseness of voice",
  "Headache",
  "Migraine-type headache",
  "Body aches",
  "Generalized weakness",
  "Fatigue",
  "Shortness of breath",
  "Difficulty breathing on exertion",
  "Wheezing",
  "Chest pain",
  "Chest tightness",
  "Palpitations",
  "Abdominal pain",
  "Upper abdominal pain",
  "Lower abdominal pain",
  "Right upper quadrant pain",
  "Nausea",
  "Vomiting",
  "Vomiting blood",
  "Diarrhea",
  "Bloody diarrhea",
  "Constipation",
  "Bloating / gas",
  "Heartburn / acidity",
  "Indigestion",
  "Loss of appetite",
  "Difficulty swallowing",
  "Dizziness / vertigo",
  "Fainting / blackout",
  "Back pain",
  "Low back pain",
  "Neck pain",
  "Joint pain",
  "Knee pain",
  "Shoulder pain",
  "Muscle pain",
  "Swelling of joints",
  "Skin rash",
  "Itching",
  "Skin lesion / boil",
  "Hair fall",
  "Earache",
  "Ear discharge",
  "Decreased hearing",
  "Eye redness",
  "Eye discharge",
  "Sore / watery eyes",
  "Blurred vision",
  "Toothache",
  "Mouth ulcers",
  "Burning micturition",
  "Frequent urination",
  "Painful urination",
  "Blood in urine",
  "Decreased urine output",
  "Weight loss",
  "Weight gain",
  "Swelling of feet",
  "Facial swelling",
  "Anxiety",
  "Low mood / depression",
  "Insomnia",
  "Excessive sleepiness",
  "Numbness / tingling",
  "Tremors",
  "Menstrual irregularity",
  "Painful periods",
  "Vaginal discharge",
  "Breast lump",
  "Follow-up visit",
  "Routine check-up",
  "Injury / trauma",
  "Animal bite",
  "Allergic reaction",
];

// Common primary-care diagnoses (type-ahead suggestions).
export const DIAGNOSES: string[] = [
  "Upper respiratory tract infection (URTI)",
  "Lower respiratory tract infection (LRTI)",
  "Acute pharyngitis",
  "Acute tonsillitis",
  "Acute laryngitis",
  "Acute bronchitis",
  "Bronchiolitis",
  "Pneumonia",
  "Asthma",
  "Asthma exacerbation",
  "COPD",
  "COPD exacerbation",
  "Allergic rhinitis",
  "Acute sinusitis",
  "Otitis media",
  "Otitis externa",
  "Conjunctivitis",
  "Acute gastroenteritis",
  "Food poisoning",
  "Acid peptic disease / GERD",
  "Gastritis",
  "Peptic ulcer disease",
  "Irritable bowel syndrome",
  "Constipation",
  "Hemorrhoids",
  "Worm infestation",
  "Hepatitis",
  "Urinary tract infection (UTI)",
  "Pyelonephritis",
  "Hypertension",
  "Newly diagnosed hypertension",
  "Type 2 diabetes mellitus",
  "Type 1 diabetes mellitus",
  "Pre-diabetes",
  "Dyslipidemia",
  "Obesity",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Anemia",
  "Iron deficiency anemia",
  "Vitamin D deficiency",
  "Vitamin B12 deficiency",
  "Migraine",
  "Tension headache",
  "Vertigo (BPPV)",
  "Dengue fever",
  "Typhoid / enteric fever",
  "Malaria",
  "Viral fever",
  "COVID-19",
  "Chikungunya",
  "Dermatitis / eczema",
  "Contact dermatitis",
  "Fungal skin infection",
  "Tinea / ringworm",
  "Scabies",
  "Cellulitis",
  "Acne",
  "Urticaria / hives",
  "Osteoarthritis",
  "Rheumatoid arthritis",
  "Gout",
  "Mechanical low back pain",
  "Sciatica",
  "Cervical spondylosis",
  "Frozen shoulder",
  "Anxiety disorder",
  "Depression",
  "Insomnia",
  "Dysmenorrhea",
  "Pelvic inflammatory disease",
  "Vaginal candidiasis",
  "Dental caries",
  "Allergic reaction",
  "Soft tissue injury",
  "Wound / laceration",
];

// Co-morbidities checklist (matches the printed prescription pad).
export const CO_MORBS: string[] = [
  "HTN",
  "DM",
  "TB",
  "Hep B",
  "Hep C",
  "Asthma",
  "IHD",
  "CKD",
];
